
services:
  gitea:
    image: docker.gitea.com/gitea:1.24.6-rootless
    env_file:
      - .env
    restart: always
    volumes:
      - ./data/gitea:/var/lib/gitea
    ports:
      - "4000:3000"
      - "2222:2222"
    profiles:
      - with-gitea

  # Hugo site generation container
  hugo-builder:
    build:
      context: ./containers/hugo-builder
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SITE_DIR=/site
    volumes:
      - site_data:/site
    restart: "no"  # Run once to build site

  hugo-debug:
    build:
      context: ./containers/hugo-builder
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SITE_DIR=/site
      - USE_LOCAL_SITE=1
    volumes:
      - site_data:/site
      - ..\ModernWikiTemplate\:/src/:ro  # Mount template config
      - ..\ModernWikiTemplate\data:/src/data/
      - ..\ModernWikiTemplate\.hugo_build.lock:/src/.hugo_build.lock
      - ..\ModernWikiTemplate\public:/src/public
    restart: "no" 
    profiles:
      - debug

  # Static site container with Caddy
  static-site:
    build:
      context: ./containers/static-site
      dockerfile: Dockerfile
    volumes:
      - site_data:/site:ro
    ports:
      - "3000:3000"
    restart: unless-stopped

  # Webhook controller container
  webhook:
    build:
      context: ./containers/webhook
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  artalk:
    image: artalk/artalk-go
    restart: unless-stopped
    ports:
      - 8080:23366
    volumes:
      - ./data/artalk:/data
    env_file:
      - .env
    environment:
      - ATK_AUTH_EMAIL_ENABLED=false

  # Entry reverse proxy container
  proxy:
    build:
      context: ./containers/proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      # Mount additional Caddyfile configurations
      - ./proxy-config:/etc/caddy/conf.d:ro
    depends_on:
      - static-site
      - webhook
    restart: unless-stopped

volumes:
  site_data:
    driver: local